"""first migration

Revision ID: 486a40dc90c4
Revises: 
Create Date: 2022-04-22 14:54:33.612529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from geoalchemy2.types import Geometry
# revision identifiers, used by Alembic.
revision = '486a40dc90c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('networks',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edges',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('network_id', postgresql.UUID(), nullable=True),
    sa.Column('source_node', sa.Unicode(), nullable=False),
    sa.Column('target_node', sa.Unicode(), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodes',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('network_id', postgresql.UUID(), nullable=True),
    sa.Column('node_id', sa.Unicode(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('type', sa.Unicode(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geo_point', Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_nodes_geo_point', 'nodes', ['geo_point'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('idx_nodes_geo_point', table_name='nodes', postgresql_using='gist', postgresql_ops={})
    op.drop_table('nodes')
    op.drop_table('edges')
    op.drop_table('networks')
    # ### end Alembic commands ###
