"""second migration

Revision ID: b1adc81e1cb8
Revises: 486a40dc90c4
Create Date: 2022-04-22 17:45:22.806693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1adc81e1cb8'
down_revision = '486a40dc90c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('radius', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'radius')
    # ### end Alembic commands ###
