"""third_migration

Revision ID: d62eff77781b
Revises: b1adc81e1cb8
Create Date: 2022-04-23 00:54:58.730702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd62eff77781b'
down_revision = 'b1adc81e1cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('parent_region_hub', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'nodes', 'nodes', ['parent_region_hub'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'parent_region_hub')
    # ### end Alembic commands ###
