openapi: 3.0.0
info:
  version: "1.0.0"
  title: Network Coverage Application
servers:
  - url: /api
# Paths supported by the server application
paths:
  /network:
    get:
      tags:
        - Network
      operationId: app.get_all_cities
      summary: Get all networks
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 0
            default: 100
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Network'
        '500':
          description: Failure
    post:
      operationId: app.api.start
      summary: Liveness check
      tags:
        - healthcheck
      responses:
        "200": {description: Success}
        "500": {description: Failure}
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                Graph File:
                  type: string
                  format: binary
    
components:
  # #   parameters:
  # #     city_id:
  # #       name: city_id
  # #       description: Unique identifier of the City
  # #     in: path
  # #     required: true
  # #     schema:
  # #       type: integer
  # #   radius:
  # #     name: radius
  # #     description: The radius value for find the nearest city
  # #     in: path
  # #     required: true
  # #     schema:
  # #       type: number
  # # securitySchemes:
  # #   jwt:
  # #     type: http
  # #     scheme: bearer
  # #     bearerFormat: JWT
  # #     x-bearerInfoFunc: app.decode_token
  schemas:
    Network:
      type: object
      required:
        - id
        - center_hub
        - latitude
        - longitude
        - region_hubs
        - towers
      properties:
        id:
          type: string
          description: Unique identifier
          example: A
          readOnly: true
        name:
          type: string
          description: Name of the center hub
          example: Mobitel-1
          minLength: 1
          maxLength: 50
        latitude:
          type: number
          description: Latitude of the center hub
          example: 10.456
        longitude:
          type: number
          description: Longitude of the center hub
          example: 50.852
        region_hubs:
          type: array
          items:
            $ref: '#/components/schemas/Network'
          description: Longitude of the center hub
          example: 50.852
          
    region_hub:
      type: object
      required:
        - id
        - name
        - latitude
        - longitude
      properties:
        id:
          type: string
          description: Unique identifier
          example: A
          readOnly: true
        name:
          type: string
          description: Name of the center hub
          example: Mobitel-1
          minLength: 1
          maxLength: 50
        latitude:
          type: number
          description: Latitude of the center hub
          example: 10.456
        longitude:
          type: number
          description: Longitude of the center hub
          example: 50.852
      
   