openapi: 3.0.0
info:
  version: "1.0.0"
  title: Network Coverage Application
servers:
  - url: /api
paths:
  /network:
    get:
      tags:
        - Network
      operationId: app.api.get_all_networks
      summary: Get all network details
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Network'
        '500':
          description: Failure
    post:
      operationId: app.api.add_network
      summary: Add new network details into the database
      tags:
        - Network
      responses:
        '201':
          description: Created
        '400':
          description: Bad request
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                Graph File:
                  type: string
                  format: binary
                  
                  
  /network/{latitude}/{longitude}:
    get:
      tags:
        - Network
      operationId: app.api.get_network_coverage
      summary: Get network coverage for given location
      parameters:
        - name: longitude
          in: path
          required: true
          schema:
            type: number
            default: -2.3302296
            minimum: -99999.99
            maximum: 99999.99
        - name: latitude
          in: path
          required: true
          schema:
            type: number
            minimum: -99999.99
            maximum: 99999.99
            default: 52.8008717
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Network'
        '400':
          description: Bad Request
  /network/cost:
    post:
      operationId: app.api.get_total_cost_for_network
      summary: Calculate cost to build a new network
      tags:
        - Network
      responses:
        '200':
          description: Created
        '400':
          description: Bad request
        '404':
          description: Not found
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                Cost File:
                  type: string
                  format: binary
                Network id:
                  type: string
      
    
    
components:
  schemas:
  
    Network:
      type: object
      required:
        - id
        - name
        - nodes
      properties:
        id:
          type: string
          description: Unique identifier
          example: d678d6d6-c2de-11ec-9d64-0242ac120002
          readOnly: true
        name:
          type: string
          description: Name of the network
          example: Mobitel
          minLength: 1
          maxLength: 50
        nodes:
          items:
            
            $ref: '#/components/schemas/Network_hub'
          description: Node details of the network
          
    Network_hub:
      type: object
      required:
        - id
        - name
        - latitude
        - longitude
        - towers
      properties:
        id:
          type: string
          description: Unique identifier
          example: B
          readOnly: true
        name:
          type: string
          description: Name of the region hub
          example: M-Region1
          minLength: 1
          maxLength: 50
        node_id:
          type: string
          description: Name of the region hub
          example: B
          minLength: 1
          maxLength: 50
        latitude:
          type: number
          description: Latitude of the region hub
          example: 9.456
        longitude:
          type: number
          description: Longitude of the region hub
          example: 51.852
        towers:
          type: array
          items:
            $ref: '#/components/schemas/Tower'
          description: Tower list of the network
          
    Tower:
      type: object
      required:
        - id
        - name
        - radius
        - latitude
        - longitude
      properties:
        id:
          type: string
          description: Unique identifier
          example: 4d69680e-e71b-4103-bc12-ebe72792d8e2
          readOnly: true
        name:
          type: string
          description: Name of the tower
          example: M-Tower1
          minLength: 1
          maxLength: 50
        node_id:
          type: string
          description: Name of the region hub
          example: C
          minLength: 1
          maxLength: 50
        radius:
          type: number
          description: Network coverage radius of the tower
          example: 11
          minLength: 1
          maxLength: 50
        latitude:
          type: number
          description: Latitude of the tower
          example: 10.456
        longitude:
          type: number
          description: Longitude of the tower
          example: 50.852
      
   